import type { PromptVersionStats, Review, ReviewReplyDraft } from "@/types/domain";

function matchesPromptVersion(draft: ReviewReplyDraft, promptId: string, version: number | undefined): boolean {
  if (draft.promptId !== promptId) return false;
  return version === undefined || draft.promptVersion === version;
}

/**
 * Aggregates every reply draft generated by one prompt — optionally scoped
 * to a single version — into approval/edit/rejection outcomes. This is the
 * data behind `PromptVersionStatsLine`: it answers "is this prompt (or this
 * specific edit of it) actually producing replies owners keep?".
 */
export function computePromptVersionStats(
  reviews: Review[],
  promptId: string,
  version?: number,
): PromptVersionStats {
  const drafts = reviews
    .flatMap((review) => review.replyDrafts)
    .filter((draft) => matchesPromptVersion(draft, promptId, version));

  const approved = drafts.filter((draft) => draft.status === "approved");
  const approvedEdited = approved.filter((draft) => draft.content.trim() !== draft.originalContent.trim());
  const rejected = drafts.filter((draft) => draft.status === "rejected");
  const pending = drafts.filter((draft) => draft.status === "pending_approval");
  const superseded = drafts.filter((draft) => draft.status === "superseded");

  const decided = drafts.filter((draft) => draft.decidedAt !== null);
  const decisionMinutes = decided.map((draft) => {
    const createdAt = new Date(draft.createdAt).getTime();
    const decidedAt = new Date(draft.decidedAt as string).getTime();
    return (decidedAt - createdAt) / 60_000;
  });

  return {
    totalGenerated: drafts.length,
    approvedCount: approved.length,
    approvedAsIsCount: approved.length - approvedEdited.length,
    approvedEditedCount: approvedEdited.length,
    rejectedCount: rejected.length,
    pendingCount: pending.length,
    supersededCount: superseded.length,
    averageDecisionMinutes:
      decisionMinutes.length > 0
        ? decisionMinutes.reduce((sum, minutes) => sum + minutes, 0) / decisionMinutes.length
        : null,
  };
}
