import type { AdminUser } from "@/types/domain";

export const MOCK_ADMIN_USERS: AdminUser[] = [
  {
    id: "user_maria",
    businessId: "business_coastal_table",
    businessName: "The Coastal Table",
    name: "Maria Delgado",
    email: "maria@coastaltable.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-02T14:12:00.000Z",
  },
  {
    id: "user_diego",
    businessId: "business_coastal_table",
    businessName: "The Coastal Table",
    name: "Diego Santos",
    email: "diego@coastaltable.com",
    role: "member",
    isActive: true,
    lastLoginAt: "2026-08-30T09:45:00.000Z",
  },
  {
    id: "user_james",
    businessId: "business_riverside_bistro",
    businessName: "Riverside Bistro",
    name: "James Whitfield",
    email: "james@riversidebistro.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-01T11:20:00.000Z",
  },
  {
    id: "user_priya",
    businessId: "business_summit_dental",
    businessName: "Summit Dental Group",
    name: "Priya Nair",
    email: "priya@summitdental.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-03T08:05:00.000Z",
  },
  {
    id: "user_dennis",
    businessId: "business_oak_hardware",
    businessName: "Oak & Iron Hardware",
    name: "Dennis Okafor",
    email: "dennis@oakironhardware.com",
    role: "owner",
    isActive: false,
    lastLoginAt: "2026-06-11T16:30:00.000Z",
  },
  {
    id: "user_lena",
    businessId: "business_bluewave_spa",
    businessName: "Bluewave Day Spa",
    name: "Lena Fischer",
    email: "lena@bluewavespa.com",
    role: "owner",
    isActive: true,
    lastLoginAt: null,
  },
  {
    id: "user_carlos",
    businessId: "business_pinecrest_auto",
    businessName: "Pinecrest Auto Repair",
    name: "Carlos Mendez",
    email: "carlos@pinecrestauto.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-08-25T10:15:00.000Z",
  },
  {
    id: "user_nadia",
    businessId: "business_harbor_dental",
    businessName: "Harbor Dental Care",
    name: "Nadia Farouk",
    email: "nadia@harbordental.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-04T08:40:00.000Z",
  },
  {
    id: "user_owen",
    businessId: "business_ironclad_gym",
    businessName: "Ironclad Gym",
    name: "Owen Castillo",
    email: "owen@ironcladgym.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-02T17:05:00.000Z",
  },
  {
    id: "user_estelle",
    businessId: "business_maple_law",
    businessName: "Maple & Co. Law",
    name: "Estelle Park",
    email: "estelle@maplelaw.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-08-29T13:50:00.000Z",
  },
  {
    id: "user_diego_alonso",
    businessId: "business_northside_vet",
    businessName: "Northside Veterinary Clinic",
    name: "Diego Alonso",
    email: "diego@northsidevet.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-03T15:25:00.000Z",
  },
  {
    id: "user_holly",
    businessId: "business_ember_bakehouse",
    businessName: "Ember Bakehouse",
    name: "Holly Bergstrom",
    email: "holly@emberbakehouse.com",
    role: "owner",
    isActive: false,
    lastLoginAt: "2026-07-02T09:15:00.000Z",
  },
  {
    id: "user_aisha",
    businessId: "business_lakeside_realty",
    businessName: "Lakeside Realty Group",
    name: "Aisha Bello",
    email: "aisha@lakesiderealty.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-05T11:00:00.000Z",
  },
  {
    id: "user_marcus",
    businessId: "business_lakeside_realty",
    businessName: "Lakeside Realty Group",
    name: "Marcus Delgado",
    email: "marcus@lakesiderealty.com",
    role: "member",
    isActive: true,
    lastLoginAt: "2026-09-01T09:30:00.000Z",
  },
];
