import type { AdminBusiness } from "@/types/domain";

export const MOCK_ADMIN_BUSINESSES: AdminBusiness[] = [
  {
    id: "business_coastal_table",
    name: "The Coastal Table",
    status: "active",
    connectionStatus: "connected",
    ownerName: "Maria Delgado",
    ownerEmail: "maria@coastaltable.com",
    userCount: 4,
    createdAt: "2025-11-02T09:00:00.000Z",
  },
  {
    id: "business_riverside_bistro",
    name: "Riverside Bistro",
    status: "active",
    connectionStatus: "needs_reauth",
    ownerName: "James Whitfield",
    ownerEmail: "james@riversidebistro.com",
    userCount: 2,
    createdAt: "2025-12-14T09:00:00.000Z",
  },
  {
    id: "business_summit_dental",
    name: "Summit Dental Group",
    status: "active",
    connectionStatus: "connected",
    ownerName: "Priya Nair",
    ownerEmail: "priya@summitdental.com",
    userCount: 11,
    createdAt: "2025-08-21T09:00:00.000Z",
  },
  {
    id: "business_oak_hardware",
    name: "Oak & Iron Hardware",
    status: "suspended",
    connectionStatus: "disconnected",
    ownerName: "Dennis Okafor",
    ownerEmail: "dennis@oakironhardware.com",
    userCount: 1,
    createdAt: "2026-01-05T09:00:00.000Z",
  },
  {
    id: "business_bluewave_spa",
    name: "Bluewave Day Spa",
    status: "active",
    connectionStatus: "connected",
    ownerName: "Lena Fischer",
    ownerEmail: "lena@bluewavespa.com",
    userCount: 3,
    createdAt: "2025-10-18T09:00:00.000Z",
  },
  {
    id: "business_pinecrest_auto",
    name: "Pinecrest Auto Repair",
    status: "active",
    connectionStatus: "needs_reauth",
    ownerName: "Carlos Mendez",
    ownerEmail: "carlos@pinecrestauto.com",
    userCount: 2,
    createdAt: "2026-02-09T09:00:00.000Z",
  },
  {
    id: "business_harbor_dental",
    name: "Harbor Dental Care",
    status: "active",
    connectionStatus: "connected",
    ownerName: "Nadia Farouk",
    ownerEmail: "nadia@harbordental.com",
    userCount: 5,
    createdAt: "2025-09-12T09:00:00.000Z",
  },
  {
    id: "business_ironclad_gym",
    name: "Ironclad Gym",
    status: "active",
    connectionStatus: "connected",
    ownerName: "Owen Castillo",
    ownerEmail: "owen@ironcladgym.com",
    userCount: 6,
    createdAt: "2025-09-28T09:00:00.000Z",
  },
  {
    id: "business_maple_law",
    name: "Maple & Co. Law",
    status: "active",
    connectionStatus: "connected",
    ownerName: "Estelle Park",
    ownerEmail: "estelle@maplelaw.com",
    userCount: 3,
    createdAt: "2025-11-20T09:00:00.000Z",
  },
  {
    id: "business_northside_vet",
    name: "Northside Veterinary Clinic",
    status: "active",
    connectionStatus: "connected",
    ownerName: "Diego Alonso",
    ownerEmail: "diego@northsidevet.com",
    userCount: 4,
    createdAt: "2025-12-30T09:00:00.000Z",
  },
  {
    id: "business_ember_bakehouse",
    name: "Ember Bakehouse",
    status: "suspended",
    connectionStatus: "connected",
    ownerName: "Holly Bergstrom",
    ownerEmail: "holly@emberbakehouse.com",
    userCount: 2,
    createdAt: "2026-01-18T09:00:00.000Z",
  },
  {
    id: "business_lakeside_realty",
    name: "Lakeside Realty Group",
    status: "active",
    connectionStatus: "connected",
    ownerName: "Aisha Bello",
    ownerEmail: "aisha@lakesiderealty.com",
    userCount: 8,
    createdAt: "2026-02-24T09:00:00.000Z",
  },
];
