import type { AdminUser } from "@/types/domain";

export const MOCK_ADMIN_USERS: AdminUser[] = [
  {
    id: "user_maria",
    businessId: "business_coastal_table",
    businessName: "The Coastal Table",
    name: "Maria Delgado",
    email: "maria@coastaltable.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-02T14:12:00.000Z",
  },
  {
    id: "user_diego",
    businessId: "business_coastal_table",
    businessName: "The Coastal Table",
    name: "Diego Santos",
    email: "diego@coastaltable.com",
    role: "member",
    isActive: true,
    lastLoginAt: "2026-08-30T09:45:00.000Z",
  },
  {
    id: "user_james",
    businessId: "business_riverside_bistro",
    businessName: "Riverside Bistro",
    name: "James Whitfield",
    email: "james@riversidebistro.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-01T11:20:00.000Z",
  },
  {
    id: "user_priya",
    businessId: "business_summit_dental",
    businessName: "Summit Dental Group",
    name: "Priya Nair",
    email: "priya@summitdental.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-09-03T08:05:00.000Z",
  },
  {
    id: "user_dennis",
    businessId: "business_oak_hardware",
    businessName: "Oak & Iron Hardware",
    name: "Dennis Okafor",
    email: "dennis@oakironhardware.com",
    role: "owner",
    isActive: false,
    lastLoginAt: "2026-06-11T16:30:00.000Z",
  },
  {
    id: "user_lena",
    businessId: "business_bluewave_spa",
    businessName: "Bluewave Day Spa",
    name: "Lena Fischer",
    email: "lena@bluewavespa.com",
    role: "owner",
    isActive: true,
    lastLoginAt: null,
  },
  {
    id: "user_carlos",
    businessId: "business_pinecrest_auto",
    businessName: "Pinecrest Auto Repair",
    name: "Carlos Mendez",
    email: "carlos@pinecrestauto.com",
    role: "owner",
    isActive: true,
    lastLoginAt: "2026-08-25T10:15:00.000Z",
  },
];
