import type { AdminBusiness } from "@/types/domain";

export const MOCK_ADMIN_BUSINESSES: AdminBusiness[] = [
  {
    id: "business_coastal_table",
    name: "The Coastal Table",
    plan: "growth",
    status: "active",
    ownerName: "Maria Delgado",
    ownerEmail: "maria@coastaltable.com",
    userCount: 4,
    createdAt: "2025-11-02T09:00:00.000Z",
  },
  {
    id: "business_riverside_bistro",
    name: "Riverside Bistro",
    plan: "starter",
    status: "active",
    ownerName: "James Whitfield",
    ownerEmail: "james@riversidebistro.com",
    userCount: 2,
    createdAt: "2025-12-14T09:00:00.000Z",
  },
  {
    id: "business_summit_dental",
    name: "Summit Dental Group",
    plan: "scale",
    status: "active",
    ownerName: "Priya Nair",
    ownerEmail: "priya@summitdental.com",
    userCount: 11,
    createdAt: "2025-08-21T09:00:00.000Z",
  },
  {
    id: "business_oak_hardware",
    name: "Oak & Iron Hardware",
    plan: "starter",
    status: "suspended",
    ownerName: "Dennis Okafor",
    ownerEmail: "dennis@oakironhardware.com",
    userCount: 1,
    createdAt: "2026-01-05T09:00:00.000Z",
  },
  {
    id: "business_bluewave_spa",
    name: "Bluewave Day Spa",
    plan: "growth",
    status: "active",
    ownerName: "Lena Fischer",
    ownerEmail: "lena@bluewavespa.com",
    userCount: 3,
    createdAt: "2025-10-18T09:00:00.000Z",
  },
  {
    id: "business_pinecrest_auto",
    name: "Pinecrest Auto Repair",
    plan: "starter",
    status: "active",
    ownerName: "Carlos Mendez",
    ownerEmail: "carlos@pinecrestauto.com",
    userCount: 2,
    createdAt: "2026-02-09T09:00:00.000Z",
  },
];
