// Post-processing for the generated axios client SDK (run by `generate:sdk:axios`).
// These steps aren't expressible in sdk-config.axios.json (the OpenAPI generator has
// no option for them), so we apply them here after generation:
// 1. Repoint package.json at the TS source (we consume source, no build step).
// 2. Strip the generator's header banner from every file. The generator templates
//    the API title + description + version into the JSDoc banner of *every* file, so
//    a one-word edit to the Swagger description (DocumentBuilder.setDescription/Title/
//    Version in bootstrap.ts) would otherwise churn a comment in all ~100 SDK files. The SDK
//    is `@ts-nocheck` and never hand-read, so the banner is dead weight — dropping it
//    keeps regen diffs limited to files whose actual shape changed.
// 3. Prepend `// @ts-nocheck` to every generated file — the SDK is always
//    auto-generated and never hand-edited, so we don't type-check/lint it
//    (avoids the generator's unused-import errors leaking into app builds).
import * as fs from 'node:fs';
import * as path from 'node:path';

const sdkDir = path.resolve(__dirname, '../client_sdk');

// The volatile header banner — the first JSDoc block, identified unambiguously by the
// generator's "auto generated by OpenAPI Generator" marker (present in every file).
const GENERATOR_BANNER = /\/\*\*[\s\S]*?auto generated by OpenAPI Generator[\s\S]*?\*\/\n?/;

// 1. Trim package.json and point entry fields at the source files.
const pkgPath = path.join(sdkDir, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
pkg.main = './index.ts';
pkg.module = './index.ts';
pkg.typings = './index.ts';
delete pkg.scripts;
delete pkg.devDependencies;
fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

// 2 + 3. Strip the generator banner, then ensure a leading `// @ts-nocheck`.
function processFile(dir: string): void {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) processFile(full);
    else if (full.endsWith('.ts')) {
      let content = fs.readFileSync(full, 'utf8');
      content = content.replace(GENERATOR_BANNER, '');
      if (!content.startsWith('// @ts-nocheck')) {
        content = `// @ts-nocheck\n${content}`;
      }
      fs.writeFileSync(full, content);
    }
  }
}
processFile(sdkDir);
